[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Fast cryptographic library for Rust (bindings to libsodium)"
documentation = "http://docs.maidsafe.net/rust_sodium/latest"
homepage = "https://maidsafe.net"
license = "MIT OR Apache-2.0"
name = "rust_sodium"
readme = "README.md"
repository = "https://github.com/maidsafe/rust_sodium"
version = "0.1.1"

[dependencies]
clippy = {version = "~0.0.85", optional = true}
libc = "~0.2.15"
rand = "~0.3.14"
rust_sodium-sys = { path = "rust_sodium-sys", version = "~0.1.1" }
rustc-serialize = { version = "~0.3.19", optional = true }
serde = { version = "~0.8.3", optional = true }
unwrap = "~1.1.0"

[dev-dependencies]
rustc-serialize = "~0.3.19"
serde = "~0.8.3"
serde_json = "~0.8.1"

[features]
benchmarks = []
default = ["rustc-serialize", "get-libsodium"]
get-libsodium = ["rust_sodium-sys/get-libsodium"]
