[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>", "dnaq"]
description = "Fast cryptographic library for Rust (bindings to libsodium)"
documentation = "http://docs.maidsafe.net/rust_sodium/latest"
homepage = "http://maidsafe.net"
license = "MIT OR Apache-2.0"
name = "rust_sodium"
readme = "README.md"
repository = "https://github.com/maidsafe/rust_sodium"
version = "0.1.0"

[dependencies]
libc = "~0.2.14"
rand = "~0.3.14"
rust_sodium-sys = { path = "rust_sodium-sys", version = "=0.1.0" }
rustc-serialize = { version = "~0.3.19", optional = true }
serde = { version = "~0.8.0", optional = true }

[dev-dependencies]
rustc-serialize = "~0.3.19"
serde = "~0.8.0"
serde_json = "~0.8.0"

[features]
benchmarks = []
default = ["rustc-serialize", "get-libsodium"]
get-libsodium = ["rust_sodium-sys/get-libsodium"]
